### ISSUE TITLE
requirements file is missing 

### ISSUE THREAD

**Issue by arf1372** [utailab/cs-portal#12]
Many people using `virtualenv` nowadays! They assume you include a `requirements.txt` file to setting up their python virtual environment So please include this piece!

**Comment by arf1372** [comment]
I, myself, could handle this one.

**Comment by mahyarap** [comment]
@arf1372 Agreed. I think we have reached a state that we can use it. Specially after that inconsistency in Django version of the team, they will understand its value.

**Comment by arf1372** [comment]
Can members let me know output of:

``` bash
$ pip freeze
```

??

Please answer below in comments on this issue and also mention me! :)

**Comment by mahyarap** [comment]
@arf1372 

```
Django==1.10
Pillow==3.3.1
```

**Comment by Alir3za97** [comment]
I have the same.
@arf1372
